### ISSUE TITLE
Update Polkadot logo

### ISSUE THREAD

**Issue by prybalko** [goldsteinsveta/web3-regular#1]
Polkadot recently updated its logo, it would be nice if `web3-regular` could reflect that.

Expected result:
![image](https://user-images.githubusercontent.com/7165377/152946360-6332c7a0-d2bf-4b5b-9ce1-4f166870517c.png)

Actual result:
![image](https://user-images.githubusercontent.com/7165377/152946394-e57de1f0-3239-4a71-b9d2-ef0116977a8c.png)

**Comment by goldsteinsveta** [comment]
thanks for the issue, the glyph is updated, see [here](https://goldsteinsveta.github.io/web3-regular/)
